version: "3"
# Список наших сервисов (контейнеров)

networks:
  network:
        driver: bridge
services:
    nginx:
        # используем последний стабильный образ nginx
        image: nginx
        container_name: nginx
        # маршрутизируем порты
        ports:
            - "443:443"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            #- ./nginx:/etc/nginx/conf.d
            - wordpress:/var/www/wordpress
            # /Users/bcherie/data/wordpress/:/usr/src/wordpress/wp-config-sample.php
            #подумать/сделать папку у себя в проекте:
            #- ./www:/var/www/html
            #- ./logs/nginx:/var/log/nginx
        # nginx должен общаться с php контейнером
        networks:
            - network
        depends_on:
            - wordpress
        build: requirements/nginx/
        restart: always
    wordpress:
        image: wordpress
        container_name: wordpress
        ports:
            - '9000'
        env_file: .env
        volumes:
            - wordpress:/var/www/wordpress
        networks:
            - network
        depends_on:
            - mysql
        build: requirements/wordpress/
        restart: always
    #php:
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
    #    build: ./images/php
        # этот образ будет общаться с mysql
     #   links:
     #       - mysql
        # монтируем директорию с проектами
     #   volumes:
     #       - ./www:/var/www
    mysql:
        image: mariadb
        container_name: mariadb
        env_file:
            - .env
        volumes:
            - mariadb:/var/lib/mysql
        networks:
            - network
        # ports:
        #     - 3306
        #- ./logs/mysql:/var/log/mysql
        #- ./mysql-files:/var/lib/mysql-files
        #- ./data:/docker-entrypoint-initdb.d
        # задаем пароль для root пользователя
        # заливку дампа сайта и создание пользователя для доступа к базе снаружи будем делать позже
        restart: always
        build: requirements/mariadb/
        #путь к файлу с переменными окружения (вместо строчек выше)
volumes:
  wordpress:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/bcherie/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/bcherie/data/mariadb
